name: Tests
on: [pull_request]
jobs:
  Run-Codecept-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - uses: ramsey/composer-install@v1
      - run: composer validate
      - name: Check PHP syntax errors
        uses: overtrue/phplint@8.2
        with:
          path: .
          options: --exclude=vendor
      - uses: actions/cache@v2
        id: cache-db
        with:
          path: ~/.symfony/cache
          key: db
      - uses: symfonycorp/security-checker-action@v4
        with:
          disable-exit-code: 1
        id: security-check
      - name: Display the vulnerabilities as JSON
        run: echo ${{ steps.security-check.outputs.vulns }}
      - run: sudo install -m 0775 -o $(id -u) -g $(id -g) -d /var/log/searchanise
      - run: composer test
